CREATE SCHEMA `zoo` ;

CREATE TABLE `zoo`.`animals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `scientific_name` VARCHAR(45) NULL,
  `life_span` INT NULL,
  `weight_lb` DECIMAL(10,2) NULL,
  `diet` VARCHAR(45) NULL,
  `endangered_status` VARCHAR(45) NULL,
  `picture` VARCHAR(170) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `animalscol_UNIQUE` (`scientific_name` ASC) VISIBLE);

-- All this info is from NC Zoo Link: https://www.nczoo.org/wildlife/animals
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (1, 'Addra Gazelle', 'Nanger dama', 11, 135, 'Herbivore', 'Critically Endangered', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-06/addra-gazelle-face-DSC6964.jpg?h=f50cdb0c&itok=FWnTI7Vt');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (2, 'African Elephant', 'Loxodonta africana', 60, 10000, 'Herbivore', 'Vulnerable', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-06/elephant-1440x675.jpg?h=ae0a076d&itok=fN8_uoM2');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (3, 'African Lion', 'Panthera leo', 15, 425, 'Carnivore', 'Vulnerable', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-06/african-lion-face-dsc0760.jpg?h=b7fba573&itok=UV5nsu6R');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (4, 'African Pancake Tortoise', 'Malacochersus tornieri', 25, 2, 'Herbivore', 'Critically Endangered', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/african-pancake-tortoise-face-dsc_8084-704-679-704.jpg?h=77055d78&itok=OqjyQi9a');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (5, 'Alligator Snapping Turtle', 'Macrochelys temminckii', 50, 175, 'Carnivore', 'Vulnerable ', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-06/alligator-snapping-turtle-dsc_1544.jpg?h=ae0a076d&itok=fe165LQ4');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (6, 'American Alligator', 'Alligator mississippiensis', 30, 400, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-05/americanalligator.jpg?h=ed12187b&itok=SWYuS6NH');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (7, 'American Bison', 'Bison bison', 15, 1000, 'Herbivore', 'Near Threatened', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-06/american-bison-face-dsc9522.jpg?h=b5e4631f&itok=ZYtbKhgh');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (8, 'Arctic Fox', 'Vulpes lagopus', 7, 7, 'Omnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/arctic-fox-dsc_4709.jpg?h=d0b47d57&itok=Iam8M1z4');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (9, 'Barking Treefrog', 'Hyla gratiosa', null, .047, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-06/barking-treefrog-dsc_2329-146.jpg?h=96a96008&itok=fYebnsuZ');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (10, 'Barred Owl', 'Strix varia', 20, 1.25, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/barred-owl-7f0a4195_1.jpg?h=90500325&itok=cNwQL3Cy');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (11, 'Beaded Lizard', 'Heloderma horridum', 30, 5, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/beaded-lizard-102.jpg?h=7d7ea208&itok=ezlxAjse');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (12, 'Black Bear', 'Ursus americanus', 22, 400, 'Omnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-06/black-bear-face-dsc_2718.jpg?h=96a96008&itok=7xEWzmDk');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (13, 'Blue-crowned Hanging Parrot', 'Loriculus galgulus', 14, .06, 'Herbivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/blue-crowned-hanging-parrot-picnicking-4918.jpg?h=95d74bef&itok=UsiaI6p8');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (14, 'Blue-tongued Skink', 'Tiliqua scincoides', null, .87, 'Omnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-06/blue-tonqued-skink-face-dsc_0936.jpg?h=96a96008&itok=YSbuhfJv');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (15, 'Bobcat', 'Lynx rufus', 12, 20, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/bobcat-dsc_5397-120-120-120.jpg?h=ba758658&itok=k-CxtXI1');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (16, 'Bongo', 'Tragelaphus eurycerus', null, 650, 'Herbivore', 'Near Threatened', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/bongo-face-picnicking-6982.jpg?h=98afb83f&itok=oUTFUKjY');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (17, 'Burrowing Owl', 'Athene cunicularia', 7, .41, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/burrowing-owl-5.jpg?h=b657a89e&itok=JOfjD9pk');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (18, 'Cape Porcupine', 'Hystrix africaeaustralis', 13, 40, 'Herbivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/cape-porcupine-face-_dsc0294.jpg?h=013f78fb&itok=5IOrnrFi');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (19, 'Chilean Flamingo', 'Phoenicopterus chilensis', 50, 6.5, 'Omnivore', 'Near Threatened', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-06/flamingo-hero-1440x635.jpg?h=a9af774a&itok=Ueh-DK15');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (20, 'Chimpanzee', 'Pan troglodytes', 40, 115, 'Omnivore', 'Endangered', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-05/chimpanzee.jpg?h=035ac227&itok=g4S9okhx');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (21, 'Copperhead', 'Agkistrodon contortrix', 18, null, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/copperhead-dsc_5966-27.jpg?h=bd1558d4&itok=763Pomsi');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (22, 'Cottonmouth', 'Agkistrodon piscivorus', 10, null, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/eastern-cottonmouth-18.jpg?h=be4c37ce&itok=sFoKJrWc');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (23, 'Cougar', 'Felis concolor', 13, 150, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/cougar-dsc_6235.jpg?h=34131f73&itok=zmGrwZLB');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (24, 'Crested Coua', 'Coua cristata', null, .78, 'Omnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/crested-coua-dsc_6888-88.jpg?h=eb1e461d&itok=ydHQ7hAo');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (25, 'Desert Pupfish', 'Cyprinodon macularius', 2, null, 'Omnivore', 'Vulnerable', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/desert-pupfish-dsc_3127-260.jpg?h=77681883&itok=1iOKQ6PO');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (26, 'Desert Tortoise', 'Gopherus agassizii', 80, 12, 'Herbivore', 'Vulnerable', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/desert-tortoise-dsc_1802-62.jpg?h=60c258d9&itok=ih-ez468');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (27, 'Elk', 'Cervus canadensis', 10, 600, 'Herbivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/elk-dsc_0525-57.jpg?h=b2599aab&itok=J03DksvX');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (28, 'Fringe-eared Oryx', 'Oryx beisa', 18, 400, 'Herbivore', 'Vulnerable ', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/fringe-eared-oryx_dsc6781.jpg?h=16a82675&itok=la3MdGak');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (29, 'Gila Monster', 'Heloderma suspectum', 20, 4, 'Carnivore', 'Near Threatened', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/gila-monster-dsc_0014-2-71.jpg?h=96a96008&itok=p8FEEtl6');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (30, 'Giraffe', 'Giraffa camelopardalis', 23, 2500, 'Herbivore', 'Vulnerable ', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/giraffe-dsc_8410_0.jpg?h=ca67864b&itok=fT3JVVCo');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (31, 'Golden-crested Myna', 'Ampeliceps coronatus', 17, .19, 'Omnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/golden-crested-mynah-140.jpg?h=18250715&itok=-KJYdTfj');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (32, 'Greater Kudu', 'Tragelaphus strepsiceros', 23, 550, 'Herbivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/greater-kudu-_dsc6760.jpg?h=c9a1cd5f&itok=8iIjMwRK');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (33, 'Hamadryas Baboon', 'Papio hamadryas', 30, 45, 'Omnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-05/hamadryasbaboon.jpg?h=1c587eb2&itok=avlZsUVq');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (34, 'Harbor Seal', 'Phoca vitulina', 25, 275, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-05/harborseal.jpg?h=6a78136f&itok=p8kl1YA6');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (35, 'Honey Bee', 'Apis mellifera', 1, .016, 'Herbivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-10/honey_bee_feature.jpg?h=4bec21c6&itok=lYpPpuw-');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (36, 'Horned Puffin', 'Fratercula corniculata', 20, 1.3, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/horned-puffin-face-puffin.jpg?h=f6190ae2&itok=8K2cT6sf');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (37, 'Laughing Kookaburra', 'Dacelo novaeguineae', 15, .88, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/laughing-kookaburra-face-2813.jpg?h=e648bc6f&itok=hQ-CQxQ9');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (38, 'Longnose Gar', 'Lepisosteus osseus', 9, 3.5, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/longnose-gar-face-longnosed_gar_nov05_-_11.jpg?h=52d3fcb6&itok=8bvTwcbt');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (39, 'Madagascar Hissing Cockroach', 'Gromphadorhina portentosa', 3, .093, 'Omnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/madagascar-hissing-cockroach-8458.jpg?h=622a27bb&itok=KmlR7-SM');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (40, 'Nicobar Pigeon', 'Caloenas nicobarica', 12, 2, 'Omnivore', 'Near Threatened', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/nicobar-pigeon-dsc6487.jpg?h=333419b6&itok=RvuxIwk5');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (41, 'North American River Otter', 'Lontra canadensis', 9, 20, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/otter-dsc_5294-89-89-89.jpg?h=ccfa8e5c&itok=y-2cN4Ed');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (42, 'Ocelot', 'Leopardus pardalis', 10, 30, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/ocelot-dsc_0640-100.jpg?h=807cd7d6&itok=gz4Jz1GG');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (43, 'Ornate Uromastyx', 'Uromastyx ornata', 20, .56, 'Herbivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/ornate-uromastyx-252.jpg?h=5ec5f776&itok=toCCGUzX');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (44, 'Ostrich', 'Struthio camelus', 35, 300, 'Omnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/ostrich-dsc6961.jpg?h=ae0a076d&itok=7V9TD5SI');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (45, 'Panamanian Golden Frog', 'Atelopus zeteki', 12, .16, 'Carnivore', 'Critically Endangered', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/panamanian-golden-frog-181.jpg?h=764a7fc8&itok=thDFBB7p');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (46, 'Polar Bear', 'Ursus maritimus', 25, 1200, 'Carnivore', 'Vulnerable', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/polar-bear-dsc_8905-73-73.jpg?h=ae0a076d&itok=lOohTbRk');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (47, 'Red River Hog', 'Potamochoerus porcus', 20, 175, 'Omnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/red-river-hog-dsc_7880.jpg?h=86784de3&itok=VPDu5Xu0');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (48, 'Red Wolf', 'Canis rufus', 6, 60, 'Carnivore', 'Critically Endangered', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/red-wolf-dsc_2947-67.jpg?h=de2b0f90&itok=ETX6tj1x');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (49, 'Red-ruffed Lemur', 'Varecia rubra', 18, 9, 'Herbivore', 'Critically Endangered', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/red-ruffed-lemur_dsc0111.jpg?h=07878c17&itok=t_eOb8w8');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (50, 'Ring-tailed Lemur', 'Lemur catta', 18, 6.5, 'Herbivore', 'Endangered', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/ring-tailed-lemur-dsc_1108.jpg?h=b99ba456&itok=RWEtmm3z');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (51, 'Sand Cat', 'Felis margarita', null, 7, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/sand-cat-face-104.jpg?h=57474f6b&itok=fEUEX-AC');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (52, 'Sidewinder', 'Crotalus cerastes', 20, .5, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/sidewinder-face-dsc_9167-105.jpg?h=978eb7d8&itok=TzKi5Xs7');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (53, 'Sitatunga', 'Tragelaphus spekii', 19, 200, 'Herbivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/sitatunga-_dsc6767.jpg?h=4dad04cc&itok=ayaEHBKD');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (54, 'Skunk (hybrid)', 'Mephitis spp.', null, 7, 'Omnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/skunk-9254.jpg?h=06933fd8&itok=o78fVmFB');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (55, 'Southern White Rhinoceros', 'Ceratotherium simum', 45, 5000, 'Herbivore', 'Near Threatened', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/rhino-dsc6219.jpg?h=11ddefa4&itok=LfS4lcpC');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (56, 'Speckled Mousebird', 'Colius striata', 8, 1.3, 'Herbivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/speckled-mousebird-901.jpg?h=349b2c56&itok=_5ZbC0hA');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (57, 'Spiny-tailed Monitor', 'Varanus acanthurus', 10, .69, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/spiny-tailed-monitor-face-6192.jpg?h=f9d4fcbf&itok=BgKNhfgW');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (58, 'Sunbittern', 'Eurypyga helias', null, .5, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/sunbittern-face-_dsc6318.jpg?h=d6a13ec4&itok=8tP983h9');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (59, 'Thomson\'s Gazelle', 'Eudorcas thomsonii', 13, 45, 'Herbivore', 'Near Threatened', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-06/thomsons-gazelle-dsc6718.jpg?h=f631fd72&itok=PS1l6t2H');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (60, 'Timber Rattlesnake', 'Crotalus horridus', 20, 1.5, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/timber-rattlesnake-face-dsc_9943-9.jpg?h=c5d4ffd1&itok=rLZWdvw6');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (61, 'Vampire Bat', 'Desmodus rotundus', 10, .078, 'Carnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/vampire-bat-face-dsc_5267.jpg?h=e249fc39&itok=sY1GT2DD');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (62, 'Victoria Crowned Pigeon', 'Goura victoria', 25, 5, 'Omnivore', 'Near Threatened', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/victoria-crowned-pigeon-face-193.jpg?h=13f8bc06&itok=Sh1rXR9p');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (63, 'Common Waterbuck', 'Kobus ellipsiprymnus', 12, 500, 'Herbivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/common-waterbuck-_dsc6956.jpg?h=08fdf000&itok=m5tdzTXR');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (64, 'Western Lowland Gorilla', 'Gorilla gorilla', 30, 350, 'Herbivore', 'Critically Endangered', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/western-gorilla-face-eating-gorilla_no_glass_-367.jpg?h=951f7d49&itok=LD8Mr_il');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (65, 'White-faced Whistling Duck', 'Dendrocygna viduata', null, 1.5, 'Omnivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-07/white-faced-whistling-duck-face-419996707_7d38ea907a_o.jpg?h=16101103&itok=aUfVu7rX');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (66, 'White-headed Mousebird', 'Colius leucocephalus', 8, 1.3, 'Herbivore', 'Least Concern', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-08/white-headed-mousebird-2516.jpg?h=ce6685d7&itok=ETDPBUef');
insert into animals (id, name, scientific_name, life_span, weight_lb, diet, endangered_status, picture) values (67, 'Zebra', 'Equus quagga', 25, 600, 'Herbivore', 'Near Threatened', 'https://www.nczoo.org/sites/default/files/styles/hero_image_small_/public/2018-05/zebra.jpg?h=4872203c&itok=M9QrrLDI');